version: '3.9'
services:

  server:
    image: node
    container_name: backend
    restart: unless-stopped
    env_file: server/.env
    volumes:
      - server:/server
    networks:
      - app
      
  client:
    image: nginx
    depends_on:
      - server
    ports:
      - 80:80
    container_name: frontend
    restart: unless-stopped
    
    volumes:
      - client:/papka
    networks:
      - app

volumes:
  server:
  client:

networks:
  app: 
    driver: bridge

    